// Auto-generated by starmetal-test-generator. Do not edit manually.
// Source fixtures: crates/starmetal-core/testing_data

// Fixture: config/01_config_parsing.json
#[test]
fn config_01_config_parsing_minimal_config() {
    // Fixture: config/01_config_parsing.json | Case: "minimal config"
    let config: starmetal_core::config::Config =
        toml::from_str("[server]\nbind = \"127.0.0.1:3000\"\n")
            .expect("fixture 'minimal config' should parse");
    assert_eq!(
        config.server.bind, "127.0.0.1:3000",
        "fixture 'minimal config' bind"
    );
    assert_eq!(
        config.storage.backend, "fs",
        "fixture 'minimal config' backend"
    );
}

#[test]
fn config_01_config_parsing_full_config() {
    // Fixture: config/01_config_parsing.json | Case: "full config"
    let config: starmetal_core::config::Config = toml::from_str("[server]\nbind = \"0.0.0.0:9090\"\n\n[storage]\nbackend = \"s3\"\n\n[storage.s3]\nbucket = \"my-bucket\"\nregion = \"us-west-2\"\n\n[upstream.pypi]\nenabled = true\nurl = \"https://pypi.org\"\n\n[policies]\nblock_unlicensed = true\nmax_vuln_severity = \"high\"\nallowed_licenses = [\"MIT\", \"Apache-2.0\"]\n\n[auth]\nenabled = true\ntokens = [\"secret-token\"]\n").expect("fixture 'full config' should parse");
    assert_eq!(
        config.server.bind, "0.0.0.0:9090",
        "fixture 'full config' bind"
    );
    assert_eq!(
        config.storage.backend, "s3",
        "fixture 'full config' backend"
    );
    assert_eq!(
        config.storage.s3.as_ref().expect("s3 config").bucket,
        "my-bucket",
        "fixture 'full config' s3 bucket"
    );
    assert!(
        config.policies.block_unlicensed,
        "fixture 'full config' block_unlicensed"
    );
    assert!(config.auth.enabled, "fixture 'full config' auth_enabled");
}

#[test]
fn config_01_config_parsing_empty_config_uses_defaults() {
    // Fixture: config/01_config_parsing.json | Case: "empty config uses defaults"
    let config: starmetal_core::config::Config =
        toml::from_str("").expect("fixture 'empty config uses defaults' should parse");
    assert_eq!(
        config.server.bind, "127.0.0.1:8080",
        "fixture 'empty config uses defaults' bind"
    );
    assert_eq!(
        config.storage.backend, "fs",
        "fixture 'empty config uses defaults' backend"
    );
}

#[test]
fn config_01_config_parsing_invalid_toml() {
    // Fixture: config/01_config_parsing.json | Case: "invalid toml"
    let result = toml::from_str::<starmetal_core::config::Config>("[server\nbind = oops");
    assert!(
        result.is_err(),
        "fixture 'invalid toml' should fail to parse"
    );
}

// Fixture: integrity/01_blake3_vectors.json
#[test]
fn integrity_01_blake3_vectors_empty_input() {
    // Fixture: integrity/01_blake3_vectors.json | Case: "empty input"
    let hash = starmetal_core::integrity::blake3_hex("".as_bytes());
    assert_eq!(
        hash, "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
        "fixture: empty input"
    );
    assert!(
        starmetal_core::integrity::verify_blake3(&bytes::Bytes::from("".to_string()), &hash),
        "fixture 'empty input': roundtrip verification failed"
    );
}

#[test]
fn integrity_01_blake3_vectors_hello_starmetal() {
    // Fixture: integrity/01_blake3_vectors.json | Case: "hello starmetal"
    let hash = starmetal_core::integrity::blake3_hex("hello starmetal".as_bytes());
    assert!(
        starmetal_core::integrity::verify_blake3(
            &bytes::Bytes::from("hello starmetal".to_string()),
            &hash
        ),
        "fixture 'hello starmetal': roundtrip verification failed"
    );
}

#[test]
fn integrity_01_blake3_vectors_binary_like_data() {
    // Fixture: integrity/01_blake3_vectors.json | Case: "binary-like data"
    let hash = starmetal_core::integrity::blake3_hex("\0\u{1}\u{2}\u{3}".as_bytes());
    assert!(
        starmetal_core::integrity::verify_blake3(
            &bytes::Bytes::from("\0\u{1}\u{2}\u{3}".to_string()),
            &hash
        ),
        "fixture 'binary-like data': roundtrip verification failed"
    );
}

// Fixture: lockfile/01_roundtrip.json
#[test]
fn lockfile_01_roundtrip_minimal_lock_file() {
    // Fixture: lockfile/01_roundtrip.json | Case: "minimal lock file"
    let lock = starmetal_core::lockfile::LockFile::from_toml("[metadata]\nschema_version = 1\ngenerated_at = \"2026-04-19T10:30:00Z\"\nstarmetal_version = \"0.1.0\"\n").expect("fixture 'minimal lock file' should parse");
    assert_eq!(
        lock.metadata.schema_version, 1,
        "fixture 'minimal lock file' schema_version"
    );
    assert_eq!(
        lock.metadata.starmetal_version, "0.1.0",
        "fixture 'minimal lock file' starmetal_version"
    );
    assert_eq!(
        lock.packages.len(),
        0,
        "fixture 'minimal lock file' package_count"
    );
    let serialized = lock.to_toml().expect("serialize lockfile");
    let reparsed = starmetal_core::lockfile::LockFile::from_toml(&serialized)
        .expect("fixture 'minimal lock file' roundtrip");
    assert_eq!(
        lock.packages.len(),
        reparsed.packages.len(),
        "fixture 'minimal lock file' roundtrip package count"
    );
}

#[test]
fn lockfile_01_roundtrip_lock_file_with_one_package() {
    // Fixture: lockfile/01_roundtrip.json | Case: "lock file with one package"
    let lock = starmetal_core::lockfile::LockFile::from_toml("[metadata]\nschema_version = 1\ngenerated_at = \"2026-04-19T10:30:00Z\"\nstarmetal_version = \"0.1.0\"\n\n[[packages]]\necosystem = \"pypi\"\nname = \"requests\"\nversion = \"2.31.0\"\nresolved_from = \"https://pypi.org\"\npinned = true\n\n[[packages.artifacts]]\nfilename = \"requests-2.31.0.tar.gz\"\nblake3 = \"abcdef1234567890\"\nsize = 110293\n").expect("fixture 'lock file with one package' should parse");
    assert_eq!(
        lock.metadata.schema_version, 1,
        "fixture 'lock file with one package' schema_version"
    );
    assert_eq!(
        lock.metadata.starmetal_version, "0.1.0",
        "fixture 'lock file with one package' starmetal_version"
    );
    assert_eq!(
        lock.packages.len(),
        1,
        "fixture 'lock file with one package' package_count"
    );
    assert_eq!(
        lock.packages[0].name, "requests",
        "fixture 'lock file with one package' first package name"
    );
    assert_eq!(
        lock.packages[0].ecosystem.to_string(),
        "pypi",
        "fixture 'lock file with one package' first package ecosystem"
    );
    let serialized = lock.to_toml().expect("serialize lockfile");
    let reparsed = starmetal_core::lockfile::LockFile::from_toml(&serialized)
        .expect("fixture 'lock file with one package' roundtrip");
    assert_eq!(
        lock.packages.len(),
        reparsed.packages.len(),
        "fixture 'lock file with one package' roundtrip package count"
    );
}

#[test]
fn lockfile_01_roundtrip_lock_file_with_multiple_ecosystems() {
    // Fixture: lockfile/01_roundtrip.json | Case: "lock file with multiple ecosystems"
    let lock = starmetal_core::lockfile::LockFile::from_toml("[metadata]\nschema_version = 1\ngenerated_at = \"2026-04-19T10:30:00Z\"\nstarmetal_version = \"0.1.0\"\n\n[[packages]]\necosystem = \"pypi\"\nname = \"requests\"\nversion = \"2.31.0\"\nresolved_from = \"https://pypi.org\"\n\n[[packages.artifacts]]\nfilename = \"requests-2.31.0.tar.gz\"\nblake3 = \"aaa\"\nsize = 100\n\n[[packages]]\necosystem = \"npm\"\nname = \"lodash\"\nversion = \"4.17.21\"\nresolved_from = \"https://registry.npmjs.org\"\n\n[[packages.artifacts]]\nfilename = \"lodash-4.17.21.tgz\"\nblake3 = \"bbb\"\nsize = 200\n").expect("fixture 'lock file with multiple ecosystems' should parse");
    assert_eq!(
        lock.metadata.schema_version, 1,
        "fixture 'lock file with multiple ecosystems' schema_version"
    );
    assert_eq!(
        lock.packages.len(),
        2,
        "fixture 'lock file with multiple ecosystems' package_count"
    );
    let serialized = lock.to_toml().expect("serialize lockfile");
    let reparsed = starmetal_core::lockfile::LockFile::from_toml(&serialized)
        .expect("fixture 'lock file with multiple ecosystems' roundtrip");
    assert_eq!(
        lock.packages.len(),
        reparsed.packages.len(),
        "fixture 'lock file with multiple ecosystems' roundtrip package count"
    );
}

// Fixture: package/01_pypi_normalization.json
#[test]
fn package_01_pypi_normalization_pypi_underscore_to_hyphen() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi underscore to hyphen"
    let pkg = starmetal_core::package::PackageName::new("my_package");
    let eco: starmetal_core::package::Ecosystem = "pypi".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "my-package",
        "fixture: pypi underscore to hyphen"
    );
}

#[test]
fn package_01_pypi_normalization_pypi_uppercase_to_lowercase() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi uppercase to lowercase"
    let pkg = starmetal_core::package::PackageName::new("MyPackage");
    let eco: starmetal_core::package::Ecosystem = "pypi".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "mypackage",
        "fixture: pypi uppercase to lowercase"
    );
}

#[test]
fn package_01_pypi_normalization_pypi_mixed_underscores_and_case() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi mixed underscores and case"
    let pkg = starmetal_core::package::PackageName::new("My_Cool_Package");
    let eco: starmetal_core::package::Ecosystem = "pypi".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "my-cool-package",
        "fixture: pypi mixed underscores and case"
    );
}

#[test]
fn package_01_pypi_normalization_pypi_already_normalized() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi already normalized"
    let pkg = starmetal_core::package::PackageName::new("requests");
    let eco: starmetal_core::package::Ecosystem = "pypi".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "requests",
        "fixture: pypi already normalized"
    );
}

#[test]
fn package_01_pypi_normalization_npm_passthrough() {
    // Fixture: package/01_pypi_normalization.json | Case: "npm passthrough"
    let pkg = starmetal_core::package::PackageName::new("lodash");
    let eco: starmetal_core::package::Ecosystem = "npm".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(result.as_ref(), "lodash", "fixture: npm passthrough");
}

#[test]
fn package_01_pypi_normalization_npm_scoped_package() {
    // Fixture: package/01_pypi_normalization.json | Case: "npm scoped package"
    let pkg = starmetal_core::package::PackageName::new("@types/node");
    let eco: starmetal_core::package::Ecosystem = "npm".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "@types/node",
        "fixture: npm scoped package"
    );
}

#[test]
fn package_01_pypi_normalization_cargo_lowercase() {
    // Fixture: package/01_pypi_normalization.json | Case: "cargo lowercase"
    let pkg = starmetal_core::package::PackageName::new("Serde");
    let eco: starmetal_core::package::Ecosystem = "cargo".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(result.as_ref(), "serde", "fixture: cargo lowercase");
}

#[test]
fn package_01_pypi_normalization_cargo_underscore_preserved() {
    // Fixture: package/01_pypi_normalization.json | Case: "cargo underscore preserved"
    let pkg = starmetal_core::package::PackageName::new("serde_json");
    let eco: starmetal_core::package::Ecosystem = "cargo".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "serde_json",
        "fixture: cargo underscore preserved"
    );
}

#[test]
fn package_01_pypi_normalization_hex_lowercase() {
    // Fixture: package/01_pypi_normalization.json | Case: "hex lowercase"
    let pkg = starmetal_core::package::PackageName::new("Phoenix");
    let eco: starmetal_core::package::Ecosystem = "hex".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(result.as_ref(), "phoenix", "fixture: hex lowercase");
}

#[test]
fn package_01_pypi_normalization_pypi_trailing_separator() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi trailing separator"
    let pkg = starmetal_core::package::PackageName::new("my_package_");
    let eco: starmetal_core::package::Ecosystem = "pypi".parse().expect("parse ecosystem");
    let result = pkg.normalized(eco);
    assert_eq!(
        result.as_ref(),
        "my-package",
        "fixture: pypi trailing separator"
    );
}

// Fixture: package/02_storage_keys.json
#[test]
fn package_02_storage_keys_pypi_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "pypi storage key"
    let artifact = starmetal_core::package::ArtifactId {
        ecosystem: "pypi".parse().expect("parse ecosystem"),
        name: starmetal_core::package::PackageName::new("requests"),
        version: "2.31.0".to_string(),
        filename: "requests-2.31.0.tar.gz".to_string(),
    };
    assert_eq!(
        artifact.storage_key(),
        "pypi/requests/2.31.0/requests-2.31.0.tar.gz",
        "fixture: pypi storage key"
    );
}

#[test]
fn package_02_storage_keys_npm_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "npm storage key"
    let artifact = starmetal_core::package::ArtifactId {
        ecosystem: "npm".parse().expect("parse ecosystem"),
        name: starmetal_core::package::PackageName::new("lodash"),
        version: "4.17.21".to_string(),
        filename: "lodash-4.17.21.tgz".to_string(),
    };
    assert_eq!(
        artifact.storage_key(),
        "npm/lodash/4.17.21/lodash-4.17.21.tgz",
        "fixture: npm storage key"
    );
}

#[test]
fn package_02_storage_keys_cargo_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "cargo storage key"
    let artifact = starmetal_core::package::ArtifactId {
        ecosystem: "cargo".parse().expect("parse ecosystem"),
        name: starmetal_core::package::PackageName::new("serde"),
        version: "1.0.200".to_string(),
        filename: "serde-1.0.200.crate".to_string(),
    };
    assert_eq!(
        artifact.storage_key(),
        "cargo/serde/1.0.200/serde-1.0.200.crate",
        "fixture: cargo storage key"
    );
}

#[test]
fn package_02_storage_keys_hex_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "hex storage key"
    let artifact = starmetal_core::package::ArtifactId {
        ecosystem: "hex".parse().expect("parse ecosystem"),
        name: starmetal_core::package::PackageName::new("phoenix"),
        version: "1.7.12".to_string(),
        filename: "phoenix-1.7.12.tar".to_string(),
    };
    assert_eq!(
        artifact.storage_key(),
        "hex/phoenix/1.7.12/phoenix-1.7.12.tar",
        "fixture: hex storage key"
    );
}

// Fixture: package/03_ecosystem_parsing.json
#[test]
fn package_03_ecosystem_parsing_pypi_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pypi lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "pypi".parse();
    let eco = result.expect("fixture 'pypi lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "pypi", "fixture: pypi lowercase");
}

#[test]
fn package_03_ecosystem_parsing_pypi_uppercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pypi uppercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "PYPI".parse();
    let eco = result.expect("fixture 'pypi uppercase' should parse successfully");
    assert_eq!(eco.to_string(), "pypi", "fixture: pypi uppercase");
}

#[test]
fn package_03_ecosystem_parsing_pypi_mixed_case() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pypi mixed case"
    let result: Result<starmetal_core::package::Ecosystem, _> = "PyPI".parse();
    let eco = result.expect("fixture 'pypi mixed case' should parse successfully");
    assert_eq!(eco.to_string(), "pypi", "fixture: pypi mixed case");
}

#[test]
fn package_03_ecosystem_parsing_npm_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "npm lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "npm".parse();
    let eco = result.expect("fixture 'npm lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "npm", "fixture: npm lowercase");
}

#[test]
fn package_03_ecosystem_parsing_npm_uppercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "npm uppercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "NPM".parse();
    let eco = result.expect("fixture 'npm uppercase' should parse successfully");
    assert_eq!(eco.to_string(), "npm", "fixture: npm uppercase");
}

#[test]
fn package_03_ecosystem_parsing_cargo_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "cargo lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "cargo".parse();
    let eco = result.expect("fixture 'cargo lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "cargo", "fixture: cargo lowercase");
}

#[test]
fn package_03_ecosystem_parsing_crates_alias() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "crates alias"
    let result: Result<starmetal_core::package::Ecosystem, _> = "crates".parse();
    let eco = result.expect("fixture 'crates alias' should parse successfully");
    assert_eq!(eco.to_string(), "cargo", "fixture: crates alias");
}

#[test]
fn package_03_ecosystem_parsing_crates_uppercase_alias() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "crates uppercase alias"
    let result: Result<starmetal_core::package::Ecosystem, _> = "CRATES".parse();
    let eco = result.expect("fixture 'crates uppercase alias' should parse successfully");
    assert_eq!(eco.to_string(), "cargo", "fixture: crates uppercase alias");
}

#[test]
fn package_03_ecosystem_parsing_hex_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "hex lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "hex".parse();
    let eco = result.expect("fixture 'hex lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "hex", "fixture: hex lowercase");
}

#[test]
fn package_03_ecosystem_parsing_hex_uppercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "hex uppercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "HEX".parse();
    let eco = result.expect("fixture 'hex uppercase' should parse successfully");
    assert_eq!(eco.to_string(), "hex", "fixture: hex uppercase");
}

#[test]
fn package_03_ecosystem_parsing_maven_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "maven lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "maven".parse();
    let eco = result.expect("fixture 'maven lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "maven", "fixture: maven lowercase");
}

#[test]
fn package_03_ecosystem_parsing_rubygems_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "rubygems lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "rubygems".parse();
    let eco = result.expect("fixture 'rubygems lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "rubygems", "fixture: rubygems lowercase");
}

#[test]
fn package_03_ecosystem_parsing_nuget_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "nuget lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "nuget".parse();
    let eco = result.expect("fixture 'nuget lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "nuget", "fixture: nuget lowercase");
}

#[test]
fn package_03_ecosystem_parsing_pub_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pub lowercase"
    let result: Result<starmetal_core::package::Ecosystem, _> = "pub".parse();
    let eco = result.expect("fixture 'pub lowercase' should parse successfully");
    assert_eq!(eco.to_string(), "pub", "fixture: pub lowercase");
}

#[test]
fn package_03_ecosystem_parsing_empty_string() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "empty string"
    let result: Result<starmetal_core::package::Ecosystem, _> = "".parse();
    let err = result.expect_err("fixture 'empty string' should produce an error");
    assert!(
        err.to_string().contains("unknown ecosystem"),
        "fixture 'empty string': error '{}' should contain 'unknown ecosystem'",
        err
    );
}

#[test]
fn package_03_ecosystem_parsing_numeric_input() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "numeric input"
    let result: Result<starmetal_core::package::Ecosystem, _> = "123".parse();
    let err = result.expect_err("fixture 'numeric input' should produce an error");
    assert!(
        err.to_string().contains("unknown ecosystem"),
        "fixture 'numeric input': error '{}' should contain 'unknown ecosystem'",
        err
    );
}

// Fixture: policy/01_policy_checks.json
#[test]
fn policy_01_policy_checks_allow_everything_by_default() {
    // Fixture: policy/01_policy_checks.json | Case: "allow everything by default"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec![],
        blocked_packages: vec![],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("requests"),
        version: "2.31.0".to_string(),
        license: Some("Apache-2.0".to_string()),
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    assert!(
        result.is_ok(),
        "fixture 'allow everything by default' should be allowed but got: {:?}",
        result
    );
}

#[test]
fn policy_01_policy_checks_block_explicitly_blocked_package() {
    // Fixture: policy/01_policy_checks.json | Case: "block explicitly blocked package"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec![],
        blocked_packages: vec!["malware-pkg".to_string()],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("malware-pkg"),
        version: "1.0.0".to_string(),
        license: Some("MIT".to_string()),
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    let err = result.expect_err("fixture 'block explicitly blocked package' should be blocked");
    assert!(
        err.to_string().contains("malware-pkg is blocked"),
        "fixture 'block explicitly blocked package': error '{}' should contain 'malware-pkg is blocked'",
        err
    );
}

#[test]
fn policy_01_policy_checks_block_unlicensed_when_configured() {
    // Fixture: policy/01_policy_checks.json | Case: "block unlicensed when configured"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: true,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec![],
        blocked_packages: vec![],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("no-license"),
        version: "0.1.0".to_string(),
        license: None,
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    let err = result.expect_err("fixture 'block unlicensed when configured' should be blocked");
    assert!(
        err.to_string().contains("no license"),
        "fixture 'block unlicensed when configured': error '{}' should contain 'no license'",
        err
    );
}

#[test]
fn policy_01_policy_checks_allow_unlicensed_when_not_configured() {
    // Fixture: policy/01_policy_checks.json | Case: "allow unlicensed when not configured"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec![],
        blocked_packages: vec![],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("no-license"),
        version: "0.1.0".to_string(),
        license: None,
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    assert!(
        result.is_ok(),
        "fixture 'allow unlicensed when not configured' should be allowed but got: {:?}",
        result
    );
}

#[test]
fn policy_01_policy_checks_block_license_not_in_allowlist() {
    // Fixture: policy/01_policy_checks.json | Case: "block license not in allowlist"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec!["MIT".to_string(), "Apache-2.0".to_string()],
        blocked_packages: vec![],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("gpl-pkg"),
        version: "1.0.0".to_string(),
        license: Some("GPL-3.0".to_string()),
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    let err = result.expect_err("fixture 'block license not in allowlist' should be blocked");
    assert!(
        err.to_string().contains("not in allowed list"),
        "fixture 'block license not in allowlist': error '{}' should contain 'not in allowed list'",
        err
    );
}

#[test]
fn policy_01_policy_checks_allow_license_in_allowlist() {
    // Fixture: policy/01_policy_checks.json | Case: "allow license in allowlist"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec!["MIT".to_string(), "Apache-2.0".to_string()],
        blocked_packages: vec![],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("good-pkg"),
        version: "1.0.0".to_string(),
        license: Some("MIT".to_string()),
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    assert!(
        result.is_ok(),
        "fixture 'allow license in allowlist' should be allowed but got: {:?}",
        result
    );
}

#[test]
fn policy_01_policy_checks_empty_allowlist_allows_all_licenses() {
    // Fixture: policy/01_policy_checks.json | Case: "empty allowlist allows all licenses"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec![],
        blocked_packages: vec![],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("any-pkg"),
        version: "1.0.0".to_string(),
        license: Some("WTFPL".to_string()),
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    assert!(
        result.is_ok(),
        "fixture 'empty allowlist allows all licenses' should be allowed but got: {:?}",
        result
    );
}

#[test]
fn policy_01_policy_checks_non_blocked_package_passes() {
    // Fixture: policy/01_policy_checks.json | Case: "non-blocked package passes"
    let policy = starmetal_core::policy::PolicyConfig {
        block_unlicensed: false,
        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),
        allowed_licenses: vec![],
        blocked_packages: vec!["other-pkg".to_string()],
    };
    let metadata = starmetal_core::package::VersionMetadata {
        name: starmetal_core::package::PackageName::new("good-pkg"),
        version: "1.0.0".to_string(),
        license: Some("MIT".to_string()),
        yanked: false,
        artifacts: vec![starmetal_core::package::ArtifactDigest {
            filename: "dummy.tar.gz".into(),
            blake3: "0".repeat(64),
            size: 0,
            upstream_hashes: ahash::AHashMap::new(),
        }],
        listed: None,
        protocol_metadata: None,
    };
    let result = policy.check(&metadata);
    assert!(
        result.is_ok(),
        "fixture 'non-blocked package passes' should be allowed but got: {:?}",
        result
    );
}
