use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use clap::Parser;
use serde::Deserialize;

/// Generates Rust integration test code from JSON fixture files.
///
/// Walks a directory of JSON fixture files conforming to the starmetal fixture
/// schema and produces a single Rust source file containing `#[test]`
/// functions for each test case.
#[derive(Parser)]
#[command(
    name = "starmetal-test-generator",
    about = "Generate tests from JSON fixtures"
)]
struct Cli {
    /// Path to the directory containing JSON fixture files
    #[arg(long)]
    fixtures: PathBuf,

    /// Path to the output Rust test file
    #[arg(long)]
    output: PathBuf,
}

/// A single test case inside a fixture file.
#[derive(Debug, Deserialize)]
struct TestCase {
    name: String,
    #[allow(dead_code)]
    description: Option<String>,
    input: serde_json::Value,
    expected: serde_json::Value,
    error: Option<String>,
}

fn main() {
    let cli = Cli::parse();

    let fixture_files = collect_fixture_files(&cli.fixtures);
    if fixture_files.is_empty() {
        eprintln!(
            "warning: no JSON fixture files found in {}",
            cli.fixtures.display()
        );
    }

    let mut output = String::new();
    writeln!(
        output,
        "// Auto-generated by starmetal-test-generator. Do not edit manually."
    )
    .unwrap();
    writeln!(output, "// Source fixtures: {}", cli.fixtures.display()).unwrap();
    writeln!(output).unwrap();

    let mut total_tests = 0usize;

    for fixture_path in &fixture_files {
        let relative = fixture_path
            .strip_prefix(&cli.fixtures)
            .unwrap_or(fixture_path);

        let content = match std::fs::read_to_string(fixture_path) {
            Ok(content) => content,
            Err(err) => {
                eprintln!("error: failed to read {}: {err}", fixture_path.display());
                std::process::exit(1);
            }
        };

        let cases: Vec<TestCase> = match serde_json::from_str(&content) {
            Ok(cases) => cases,
            Err(err) => {
                eprintln!("error: failed to parse {}: {err}", fixture_path.display());
                std::process::exit(1);
            }
        };

        // Derive a module-level prefix from the fixture path.
        let module_prefix = derive_module_prefix(relative);

        // Detect category from the first directory component of the relative path.
        let category = detect_category(relative);

        writeln!(output, "// Fixture: {}", relative.display()).unwrap();

        for case in &cases {
            let function_name = make_function_name(&module_prefix, &case.name);
            generate_test_function(&mut output, &function_name, case, relative, &category);
            total_tests += 1;
        }

        writeln!(output).unwrap();
    }

    if let Some(parent) = cli.output.parent()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent).unwrap_or_else(|err| {
            eprintln!(
                "error: failed to create directory {}: {err}",
                parent.display()
            );
            std::process::exit(1);
        });
    }

    std::fs::write(&cli.output, &output).unwrap_or_else(|err| {
        eprintln!("error: failed to write {}: {err}", cli.output.display());
        std::process::exit(1);
    });

    eprintln!(
        "generated {total_tests} test(s) from {} fixture file(s) -> {}",
        fixture_files.len(),
        cli.output.display()
    );
}

/// Collects all `.json` files under `directory`, excluding the schema file,
/// sorted by path for deterministic output.
fn collect_fixture_files(directory: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = walkdir::WalkDir::new(directory)
        .sort_by_file_name()
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().is_file())
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "json"))
        .filter(|entry| {
            // Skip the schema file itself.
            !entry
                .file_name()
                .to_str()
                .is_some_and(|name| name.starts_with("00-"))
        })
        .map(|entry| entry.into_path())
        .collect();

    files.sort();
    files
}

/// Derives a module prefix from the fixture's relative path.
///
/// For example, `config/01_config_parsing.json` becomes `config_01_config_parsing`.
fn derive_module_prefix(relative_path: &Path) -> String {
    let stem = relative_path.with_extension("");
    let raw = stem
        .to_string_lossy()
        .replace(['/', '\\'], "_")
        .replace('-', "_");
    sanitize_identifier(&raw)
}

/// Detects the fixture category from the first directory component.
fn detect_category(relative_path: &Path) -> String {
    relative_path
        .components()
        .next()
        .and_then(|c| c.as_os_str().to_str())
        .unwrap_or("unknown")
        .to_string()
}

/// Converts a test case name into a valid Rust function name.
fn make_function_name(prefix: &str, case_name: &str) -> String {
    let suffix = case_name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '_', "_")
        .replace("__", "_")
        .trim_matches('_')
        .to_string();

    let raw = format!("{prefix}_{suffix}");
    sanitize_identifier(&raw)
}

/// Ensures the string is a valid Rust identifier.
fn sanitize_identifier(input: &str) -> String {
    let mut result: String = input
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();

    // Collapse consecutive underscores.
    while result.contains("__") {
        result = result.replace("__", "_");
    }

    // Strip leading/trailing underscores.
    result = result.trim_matches('_').to_string();

    // Prefix with underscore if it starts with a digit.
    if result.starts_with(|c: char| c.is_ascii_digit()) {
        result = format!("_{result}");
    }

    // Fallback for empty.
    if result.is_empty() {
        result = "unnamed_test".to_string();
    }

    result
}

/// Generates a single `#[test]` function for a test case,
/// dispatching to the appropriate category-specific generator.
fn generate_test_function(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
    category: &str,
) {
    match category {
        "package" => generate_package_test(output, function_name, case, fixture_path),
        "integrity" => generate_integrity_test(output, function_name, case, fixture_path),
        "policy" => generate_policy_test(output, function_name, case, fixture_path),
        "config" => generate_config_test(output, function_name, case, fixture_path),
        "lockfile" => generate_lockfile_test(output, function_name, case, fixture_path),
        _ => generate_fallback_test(output, function_name, case, fixture_path),
    }
}

/// Generate test for package category fixtures.
fn generate_package_test(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let fixture_name = &case.name;

    // Detect sub-type based on expected keys and input keys.
    let has_normalized = case.expected.get("normalized").is_some();
    let has_key = case.expected.get("key").is_some();
    let has_value_input = case.input.get("value").is_some();

    if has_normalized {
        // Normalization test
        let input_name = case.input["name"].as_str().unwrap_or("");
        let input_ecosystem = case.input["ecosystem"].as_str().unwrap_or("");
        let expected_normalized = case.expected["normalized"].as_str().unwrap_or("");

        writeln!(output, "#[test]").unwrap();
        writeln!(output, "fn {function_name}() {{").unwrap();
        writeln!(
            output,
            "    // Fixture: {} | Case: {fixture_name:?}",
            fixture_path.display()
        )
        .unwrap();
        writeln!(
            output,
            "    let pkg = starmetal_core::package::PackageName::new({:?});",
            input_name
        )
        .unwrap();
        writeln!(
            output,
            "    let eco: starmetal_core::package::Ecosystem = {:?}.parse().expect(\"parse ecosystem\");",
            input_ecosystem
        )
        .unwrap();
        writeln!(output, "    let result = pkg.normalized(eco);").unwrap();
        writeln!(
            output,
            "    assert_eq!(result.as_ref(), {:?}, \"fixture: {}\");",
            expected_normalized, fixture_name
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    } else if has_key {
        // Storage key test
        let ecosystem = case.input["ecosystem"].as_str().unwrap_or("");
        let name = case.input["name"].as_str().unwrap_or("");
        let version = case.input["version"].as_str().unwrap_or("");
        let filename = case.input["filename"].as_str().unwrap_or("");
        let expected_key = case.expected["key"].as_str().unwrap_or("");

        writeln!(output, "#[test]").unwrap();
        writeln!(output, "fn {function_name}() {{").unwrap();
        writeln!(
            output,
            "    // Fixture: {} | Case: {fixture_name:?}",
            fixture_path.display()
        )
        .unwrap();
        writeln!(
            output,
            "    let artifact = starmetal_core::package::ArtifactId {{"
        )
        .unwrap();
        writeln!(
            output,
            "        ecosystem: {:?}.parse().expect(\"parse ecosystem\"),",
            ecosystem
        )
        .unwrap();
        writeln!(
            output,
            "        name: starmetal_core::package::PackageName::new({:?}),",
            name
        )
        .unwrap();
        writeln!(output, "        version: {:?}.to_string(),", version).unwrap();
        writeln!(output, "        filename: {:?}.to_string(),", filename).unwrap();
        writeln!(output, "    }};").unwrap();
        writeln!(
            output,
            "    assert_eq!(artifact.storage_key(), {:?}, \"fixture: {}\");",
            expected_key, fixture_name
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    } else if has_value_input {
        // Ecosystem parsing test
        let input_value = case.input["value"].as_str().unwrap_or("");

        writeln!(output, "#[test]").unwrap();
        writeln!(output, "fn {function_name}() {{").unwrap();
        writeln!(
            output,
            "    // Fixture: {} | Case: {fixture_name:?}",
            fixture_path.display()
        )
        .unwrap();
        writeln!(
            output,
            "    let result: Result<starmetal_core::package::Ecosystem, _> = {:?}.parse();",
            input_value
        )
        .unwrap();

        match &case.error {
            Some(error_str) => {
                writeln!(
                    output,
                    "    let err = result.expect_err(\"fixture '{}' should produce an error\");",
                    fixture_name
                )
                .unwrap();
                writeln!(
                    output,
                    "    assert!(err.to_string().contains({:?}), \"fixture '{}': error '{{}}' should contain '{}'\", err);",
                    error_str, fixture_name, error_str
                )
                .unwrap();
            }
            None => {
                let expected_eco = case.expected["ecosystem"].as_str().unwrap_or("");
                writeln!(
                    output,
                    "    let eco = result.expect(\"fixture '{}' should parse successfully\");",
                    fixture_name
                )
                .unwrap();
                writeln!(
                    output,
                    "    assert_eq!(eco.to_string(), {:?}, \"fixture: {}\");",
                    expected_eco, fixture_name
                )
                .unwrap();
            }
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    } else {
        generate_fallback_test(output, function_name, case, fixture_path);
    }
}

/// Generate test for integrity category fixtures.
fn generate_integrity_test(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let fixture_name = &case.name;
    let input_data = case.input["data"].as_str().unwrap_or("");
    let expected_blake3 = case.expected.get("blake3");

    writeln!(output, "#[test]").unwrap();
    writeln!(output, "fn {function_name}() {{").unwrap();
    writeln!(
        output,
        "    // Fixture: {} | Case: {fixture_name:?}",
        fixture_path.display()
    )
    .unwrap();
    writeln!(
        output,
        "    let hash = starmetal_core::integrity::blake3_hex({:?}.as_bytes());",
        input_data
    )
    .unwrap();

    // If expected.blake3 is a non-null string, assert exact match.
    if let Some(serde_json::Value::String(expected_hash)) = expected_blake3 {
        writeln!(
            output,
            "    assert_eq!(hash, {:?}, \"fixture: {}\");",
            expected_hash, fixture_name
        )
        .unwrap();
    }

    // Always verify roundtrip.
    writeln!(
        output,
        "    assert!(starmetal_core::integrity::verify_blake3(&bytes::Bytes::from({:?}.to_string()), &hash), \"fixture '{}': roundtrip verification failed\");",
        input_data, fixture_name
    )
    .unwrap();

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

/// Generate test for policy category fixtures.
fn generate_policy_test(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let fixture_name = &case.name;
    let policy = &case.input["policy"];
    let package = &case.input["package"];

    let block_unlicensed = policy["block_unlicensed"].as_bool().unwrap_or(false);
    let blocked_packages = policy["blocked_packages"]
        .as_array()
        .map(|a| a.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>())
        .unwrap_or_default();
    let allowed_licenses = policy["allowed_licenses"]
        .as_array()
        .map(|a| a.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>())
        .unwrap_or_default();

    let pkg_name = package["name"].as_str().unwrap_or("");
    let pkg_version = package["version"].as_str().unwrap_or("");
    let pkg_license = package.get("license");
    let pkg_yanked = package["yanked"].as_bool().unwrap_or(false);

    let expected_allowed = case.expected["allowed"].as_bool().unwrap_or(true);

    writeln!(output, "#[test]").unwrap();
    writeln!(output, "fn {function_name}() {{").unwrap();
    writeln!(
        output,
        "    // Fixture: {} | Case: {fixture_name:?}",
        fixture_path.display()
    )
    .unwrap();
    writeln!(
        output,
        "    let policy = starmetal_core::policy::PolicyConfig {{"
    )
    .unwrap();
    writeln!(output, "        block_unlicensed: {block_unlicensed},").unwrap();
    writeln!(
        output,
        "        max_vuln_severity: starmetal_core::policy::VulnSeverity::default(),"
    )
    .unwrap();

    // Allowed licenses
    write!(output, "        allowed_licenses: vec![").unwrap();
    for (i, lic) in allowed_licenses.iter().enumerate() {
        if i > 0 {
            write!(output, ", ").unwrap();
        }
        write!(output, "{:?}.to_string()", lic).unwrap();
    }
    writeln!(output, "],").unwrap();

    // Blocked packages
    write!(output, "        blocked_packages: vec![").unwrap();
    for (i, pkg) in blocked_packages.iter().enumerate() {
        if i > 0 {
            write!(output, ", ").unwrap();
        }
        write!(output, "{:?}.to_string()", pkg).unwrap();
    }
    writeln!(output, "],").unwrap();

    writeln!(output, "    }};").unwrap();

    // Build metadata
    writeln!(
        output,
        "    let metadata = starmetal_core::package::VersionMetadata {{"
    )
    .unwrap();
    writeln!(
        output,
        "        name: starmetal_core::package::PackageName::new({:?}),",
        pkg_name
    )
    .unwrap();
    writeln!(output, "        version: {:?}.to_string(),", pkg_version).unwrap();

    // License: handle null vs string
    match pkg_license {
        Some(serde_json::Value::String(s)) => {
            writeln!(output, "        license: Some({:?}.to_string()),", s).unwrap();
        }
        _ => {
            writeln!(output, "        license: None,").unwrap();
        }
    }

    writeln!(output, "        yanked: {pkg_yanked},").unwrap();
    writeln!(
        output,
        "        artifacts: vec![starmetal_core::package::ArtifactDigest {{"
    )
    .unwrap();
    writeln!(output, "            filename: \"dummy.tar.gz\".into(),").unwrap();
    writeln!(output, "            blake3: \"0\".repeat(64),").unwrap();
    writeln!(output, "            size: 0,").unwrap();
    writeln!(
        output,
        "            upstream_hashes: ahash::AHashMap::new(),"
    )
    .unwrap();
    writeln!(output, "        }}],").unwrap();
    writeln!(output, "    }};").unwrap();

    writeln!(output, "    let result = policy.check(&metadata);").unwrap();

    if expected_allowed {
        writeln!(
            output,
            "    assert!(result.is_ok(), \"fixture '{}' should be allowed but got: {{:?}}\", result);",
            fixture_name
        )
        .unwrap();
    } else {
        let error_str = case.error.as_deref().unwrap_or("");
        writeln!(
            output,
            "    let err = result.expect_err(\"fixture '{}' should be blocked\");",
            fixture_name
        )
        .unwrap();
        writeln!(
            output,
            "    assert!(err.to_string().contains({:?}), \"fixture '{}': error '{{}}' should contain '{}'\", err);",
            error_str, fixture_name, error_str
        )
        .unwrap();
    }

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

/// Generate test for config category fixtures.
fn generate_config_test(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let fixture_name = &case.name;
    let toml_input = case.input["toml"].as_str().unwrap_or("");

    writeln!(output, "#[test]").unwrap();
    writeln!(output, "fn {function_name}() {{").unwrap();
    writeln!(
        output,
        "    // Fixture: {} | Case: {fixture_name:?}",
        fixture_path.display()
    )
    .unwrap();

    if let Some(error_str) = &case.error {
        // Error case
        writeln!(
            output,
            "    let result = toml::from_str::<starmetal_core::config::Config>({:?});",
            toml_input
        )
        .unwrap();
        writeln!(
            output,
            "    assert!(result.is_err(), \"fixture '{}' should fail to parse\");",
            fixture_name
        )
        .unwrap();
        let _ = error_str; // We just verify is_err
    } else {
        // Success case
        writeln!(
            output,
            "    let config: starmetal_core::config::Config = toml::from_str({:?}).expect(\"fixture '{}' should parse\");",
            toml_input, fixture_name
        )
        .unwrap();

        if let Some(bind) = case.expected.get("bind").and_then(|v| v.as_str()) {
            writeln!(
                output,
                "    assert_eq!(config.server.bind, {:?}, \"fixture '{}' bind\");",
                bind, fixture_name
            )
            .unwrap();
        }
        if let Some(backend) = case
            .expected
            .get("storage_backend")
            .and_then(|v| v.as_str())
        {
            writeln!(
                output,
                "    assert_eq!(config.storage.backend, {:?}, \"fixture '{}' backend\");",
                backend, fixture_name
            )
            .unwrap();
        }
        if let Some(bucket) = case.expected.get("s3_bucket").and_then(|v| v.as_str()) {
            writeln!(
                output,
                "    assert_eq!(config.storage.s3.as_ref().expect(\"s3 config\").bucket, {:?}, \"fixture '{}' s3 bucket\");",
                bucket, fixture_name
            )
            .unwrap();
        }
        if let Some(block) = case
            .expected
            .get("block_unlicensed")
            .and_then(|v| v.as_bool())
        {
            if block {
                writeln!(
                    output,
                    "    assert!(config.policies.block_unlicensed, \"fixture '{}' block_unlicensed\");",
                    fixture_name
                )
                .unwrap();
            } else {
                writeln!(
                    output,
                    "    assert!(!config.policies.block_unlicensed, \"fixture '{}' block_unlicensed\");",
                    fixture_name
                )
                .unwrap();
            }
        }
        if let Some(auth) = case.expected.get("auth_enabled").and_then(|v| v.as_bool()) {
            if auth {
                writeln!(
                    output,
                    "    assert!(config.auth.enabled, \"fixture '{}' auth_enabled\");",
                    fixture_name
                )
                .unwrap();
            } else {
                writeln!(
                    output,
                    "    assert!(!config.auth.enabled, \"fixture '{}' auth_enabled\");",
                    fixture_name
                )
                .unwrap();
            }
        }
    }

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

/// Generate test for lockfile category fixtures.
fn generate_lockfile_test(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let fixture_name = &case.name;
    let toml_input = case.input["toml"].as_str().unwrap_or("");

    writeln!(output, "#[test]").unwrap();
    writeln!(output, "fn {function_name}() {{").unwrap();
    writeln!(
        output,
        "    // Fixture: {} | Case: {fixture_name:?}",
        fixture_path.display()
    )
    .unwrap();

    if case.error.is_some() {
        writeln!(
            output,
            "    assert!(starmetal_core::lockfile::LockFile::from_toml({:?}).is_err(), \"fixture '{}' should fail\");",
            toml_input, fixture_name
        )
        .unwrap();
    } else {
        writeln!(
            output,
            "    let lock = starmetal_core::lockfile::LockFile::from_toml({:?}).expect(\"fixture '{}' should parse\");",
            toml_input, fixture_name
        )
        .unwrap();

        if let Some(sv) = case.expected.get("schema_version").and_then(|v| v.as_u64()) {
            writeln!(
                output,
                "    assert_eq!(lock.metadata.schema_version, {}, \"fixture '{}' schema_version\");",
                sv, fixture_name
            )
            .unwrap();
        }
        if let Some(dv) = case
            .expected
            .get("starmetal_version")
            .and_then(|v| v.as_str())
        {
            writeln!(
                output,
                "    assert_eq!(lock.metadata.starmetal_version, {:?}, \"fixture '{}' starmetal_version\");",
                dv, fixture_name
            )
            .unwrap();
        }
        if let Some(count) = case.expected.get("package_count").and_then(|v| v.as_u64()) {
            writeln!(
                output,
                "    assert_eq!(lock.packages.len(), {}, \"fixture '{}' package_count\");",
                count, fixture_name
            )
            .unwrap();
        }
        if let Some(name) = case
            .expected
            .get("first_package_name")
            .and_then(|v| v.as_str())
        {
            writeln!(
                output,
                "    assert_eq!(lock.packages[0].name, {:?}, \"fixture '{}' first package name\");",
                name, fixture_name
            )
            .unwrap();
        }
        if let Some(eco) = case
            .expected
            .get("first_package_ecosystem")
            .and_then(|v| v.as_str())
        {
            writeln!(
                output,
                "    assert_eq!(lock.packages[0].ecosystem.to_string(), {:?}, \"fixture '{}' first package ecosystem\");",
                eco, fixture_name
            )
            .unwrap();
        }

        // Roundtrip: serialize and re-parse
        writeln!(
            output,
            "    let serialized = lock.to_toml().expect(\"serialize lockfile\");"
        )
        .unwrap();
        writeln!(
            output,
            "    let reparsed = starmetal_core::lockfile::LockFile::from_toml(&serialized).expect(\"fixture '{}' roundtrip\");",
            fixture_name
        )
        .unwrap();
        writeln!(
            output,
            "    assert_eq!(lock.packages.len(), reparsed.packages.len(), \"fixture '{}' roundtrip package count\");",
            fixture_name
        )
        .unwrap();
    }

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

/// Fallback test generator for unknown categories.
fn generate_fallback_test(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let input_json = serde_json::to_string(&case.input).unwrap();
    let expected_json = serde_json::to_string(&case.expected).unwrap();

    writeln!(output, "#[test]").unwrap();
    writeln!(output, "fn {function_name}() {{").unwrap();
    writeln!(
        output,
        "    // Fixture: {} | Case: {:?}",
        fixture_path.display(),
        case.name
    )
    .unwrap();
    writeln!(
        output,
        "    let _input: serde_json::Value = serde_json::from_str(r#\"{}\"#).expect(\"parse input\");",
        escape_raw_string(&input_json)
    )
    .unwrap();
    writeln!(
        output,
        "    let _expected: serde_json::Value = serde_json::from_str(r#\"{}\"#).expect(\"parse expected\");",
        escape_raw_string(&expected_json)
    )
    .unwrap();

    match &case.error {
        Some(error_substring) => {
            writeln!(
                output,
                "    assert!(!{:?}.is_empty(), \"error case must have non-empty error substring\");",
                error_substring
            )
            .unwrap();
        }
        None => {
            writeln!(
                output,
                "    assert!(_expected.is_object(), \"expected must be a JSON object\");"
            )
            .unwrap();
        }
    }

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

/// Escapes content that could break a `r#"..."#` raw string literal.
fn escape_raw_string(input: &str) -> String {
    input.replace("\"#", "\\\"#")
}
