[package]
name = "starmetal-integration-tests"
description = "Integration tests for starmetal"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ahash.workspace = true
axum.workspace = true
starmetal-adapters = { workspace = true, features = [
  "cargo-registry",
  "go",
  "hex",
  "maven",
  "npm",
  "nuget",
  "pypi",
  "pub",
  "rubygems",
] }
starmetal-core.workspace = true
starmetal-git = { workspace = true, features = ["gix-backend"] }
starmetal-server = { workspace = true, features = [
  "cargo-registry",
  "go",
  "hex",
  "maven",
  "npm",
  "nuget",
  "pypi",
  "pub",
  "rubygems",
] }
starmetal-service.workspace = true
starmetal-storage = { workspace = true, features = ["backend-memory"] }
tempfile.workspace = true
tokio.workspace = true

[dev-dependencies]
bytes.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
zip.workspace = true
