#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <version> <source-sha256>" >&2
  exit 1
fi

VERSION="$1"
SHA256="$2"
BASE="https://github.com/Goldziher/starmetal/archive/refs/tags/v${VERSION}.tar.gz"

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Starmetal < Formula
  desc "High-performance self-hosted package registry and registry proxy"
  homepage "https://github.com/Goldziher/starmetal"
  url "${BASE}"
  sha256 "${SHA256}"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/starmetal-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sm --version")
  end
end
EOF
